use_frameworks!
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Jelly_Example' do
  pod 'Jelly', :path => '../'

  target 'Jelly_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
